<a href="https://colab.research.google.com/github/Tomek236/Colab-google/blob/master/%C4%86wiczenia1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

In [4]:
A.all()

True

In [5]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])

In [6]:
A.all(axis=1)

array([ True,  True])

In [7]:
B.all()

False

In [8]:
C.all()

False

In [9]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [11]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

In [12]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [13]:
np.allclose(A,B)

True

In [14]:
A == B

array([False, False,  True])

In [15]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [16]:
A > B

array([ True, False, False, False])

In [18]:
np.zeros(shape=[4,4],dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [23]:
np.ones(shape=[10,10], dtype='float') * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])